# Allows Scrapy and MongoDB to work together in separate containers through
# docker-compose: https://docs.docker.com/compose/.
# For info on use, see the README.md.
version: '3.5'
services:
  crawler_api:
    build: scrapy/schools # Build the Scrapy Dockerfile.
    depends_on:
      - mongodb_container
      - redis
    ports:
      - 5000
    network_mode: host
    volumes:
      - crawler_api:/code/schools/spiders
  # credit: https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
  # note there is no MongoDB authentication currently.
  mongodb_container:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "27000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mdipass
    volumes:
      - /vol_b/data/mongodata_test:/data/db/
  redis:
    image: redis:latest
    network_mode: host
    ports:
      - "6379"
        #    command: rq worker crawling-tasks
  redis_worker:
    build: scrapy/schools
    depends_on:
      - mongodb_container
      - redis
    command: rq worker crawling-tasks --path /code/schools/
    volumes:
      - crawler_api:/code/schools/spiders


volumes:
  mongodb_data_container:
  crawler_api:
